oyvindberg/bleep

- bleep-core/src/main/scala/bleep/package.scala
- bleep.json
- bleep/src/main/scala/bleep/BleepCommands.scala
- bleep/src/main/scala/bleep/Main.scala
- build.sbt
It's not perfect but it gives a good baseline to continue working on it.
> feat: use decline to parse command line inputs

- bleep-core/src/main/scala/bleep/LogPatterns.scala
- bleep-core/src/main/scala/bleep/bootstrap.scala
- bleep-core/src/main/scala/bleep/generateBloopFiles.scala
- bleep-core/src/main/scala/bleep/logging/LogLevel.scala
- bleep-core/src/main/scala/bleep/logging/Logger.scala
- bleep-core/src/main/scala/bleep/logging/LoggerFn.scala
- bleep-core/src/main/scala/bleep/logging/Pattern.scala
- bleep-core/src/main/scala/bleep/logging/package.scala
- bleep/src/main/scala/bleep/BleepCommand.scala
- bleep/src/main/scala/bleep/BleepCommandRemote.scala
- bleep/src/main/scala/bleep/Main.scala
- bleep/src/main/scala/bleep/commands/Clean.scala
- bleep/src/main/scala/bleep/internal/BspClientDisplayProgress.scala
- infrastructure/src/main/scala/bleep.infra/GenNativeImage.scala
https://user-images.githubusercontent.com/247937/143143627-027a5948-66db-4f38-9ee3-6506e37c58c9.mp4
> Better interface

- bleep/src/main/scala/bleep/Main.scala
- bleep/src/main/scala/com/monovore/decline/Completer.scala
- bleep/src/test/scala/com/monovore/decline/CompleterTest.scala
- bleep_completions.sh
Super irritating that decline doesn't have tab completions. I managed to implement it though, with a hack or two.
https://user-images.githubusercontent.com/247937/143333346-8b243f18-3cae-4ba0-9cfd-71aadf17361c.mp4
> Add bash tab completion (Fixes #11)

- bleep-core/src/main/scala/bleep/Defaults.scala
- bleep-core/src/main/scala/bleep/Versions.scala
- bleep-core/src/main/scala/bleep/generateBloopFiles.scala
- bleep-core/src/main/scala/bleep/internal/ScalaVersions.scala
- bleep-core/src/main/scala/bleep/model.scala
- bleep.json
- bleep/src/main/scala/bleep/Templates.scala
- bleep/src/main/scala/bleep/deduplicateBuild.scala
- bleep/src/main/scala/bleep/importBloopFilesFromSbt.scala
to be properly able to inherit platform name in json
> flatten platform hierarchy 

- .github/workflows/build.yml
- bleep/src/main/scala/bleep/BleepCommandRemote.scala
- bleep/src/main/scala/bleep/Main.scala
- bleep/src/main/scala/bleep/bsp/BspImpl.scala
- bleep/src/main/scala/bleep/bsp/CompileServerConfig.scala
- bleep/src/main/scala/bleep/bsp/SetupBloopRifle.scala
- bleep/src/main/scala/bleep/commands/Compile.scala
- bleep/src/main/scala/bleep/commands/CompileServerStart.scala
- bleep/src/main/scala/bleep/commands/CompileServerStop.scala
- bleep/src/main/scala/bleep/commands/Run.scala
- bleep/src/main/scala/bleep/commands/Script.scala
- bleep/src/main/scala/bleep/commands/Test.scala
Extracted from #97 .
Decide when to start/stop bloop in this PR
> Compile server commands

- bleep-core/src/main/scala/bleep/packaging/PackagePlugin.scala
- bleep-core/src/main/scala/bleep/packaging/Scripts.scala
- bleep-core/src/main/scala/bleep/packaging/types.scala
- bleep-tasks/src/main/scala/bleep/tasks/package.scala
- scripts/src/main/scala/bleep/scripts/GenNativeImage.scala
- Inline native plugin
- fix packaging paths
> Fix packaging

- bleep-core/src/main/scala/bleep/GenBloopFiles.scala
- bleep-core/src/main/scala/bleep/Versions.scala
- bleep-core/src/main/scala/bleep/internal/ScalaVersions.scala
- bleep-core/src/main/scala/bleep/model.scala
- bleep.json
- bleep/src/main/scala/bleep/commands/BuildCreateNew.scala
- bleep/src/main/scala/bleep/internal/importBloopFilesFromSbt.scala
- snapshot-tests/converter/bleep.json
- snapshot-tests/create-new-build/.bleep/.bloop/myapp-test@js213.json
- snapshot-tests/create-new-build/.bleep/.bloop/myapp-test@js3.json
- snapshot-tests/create-new-build/.bleep/.bloop/myapp@js213.json
- snapshot-tests/create-new-build/.bleep/.bloop/myapp@js3.json
- snapshot-tests/create-new-build/bleep.json
- snapshot-tests/doobie/bleep.json
- snapshot-tests/http4s/bleep.json
- snapshot-tests/tapir/bleep.json
from the explicit list of deps. these will be inferred from the other structures
> Drop scala and platform deps

- bleep-cli/src/main/scala/bleep/Main.scala
- bleep-cli/src/main/scala/bleep/commands/BuildDiff.scala
- bleep-cli/src/test/scala/bleep/CreateNewSnapshotTests.scala
- bleep-cli/src/test/scala/bleep/IntegrationSnapshotTests.scala
- bleep-core/src/main/scala/bleep/BuildLoader.scala
- bleep-core/src/main/scala/bleep/BuildPaths.scala
- bleep.yaml
when you make changes to a build you can see the effective changes with this command. it also works for arbitrary git revisions in the past
> Add `build diff` command

- bleep-core/src/scala/bleep/GenBloopFiles.scala
- bleep-core/src/scala/bleep/Versions.scala
- bleep-core/src/scala/bleep/internal/ScalaVersions.scala
> Initial native support

- bleep.yaml
- bloop-config
- bloop-rifle
- coursier
- librarymanagement-core
- jsoup
> Update some deps

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/commands/BuildUpdateDeps.scala
- bleep-core/src/scala/bleep/BleepCacheLogger.scala
- bleep-core/src/scala/bleep/CoursierResolver.scala
- bleep-core/src/scala/bleep/Started.scala
- bleep-core/src/scala/bleep/bootstrap.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
- bleep-model/src/scala/bleep/FetchBleepRelease.scala
- bleep-model/src/scala/bleep/FetchJvm.scala
- bleep-model/src/scala/bleep/FetchNode.scala
- bleep.yaml
so it'll be easy to download and use bleep from applications, for instance
> Move fetchers all the way up to `bleep-model`

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/commands/Scalafmt.scala
- bleep-model/src/scala/bleep/FetchScalafmt.scala
downloads scalafmt native build based on the requested version in `.scalafmt.conf`.
https://user-images.githubusercontent.com/247937/199134193-47abaad4-384e-4d56-b70d-347461c93837.mp4
> add `fmt` command

- .github/workflows/build.yml
- bleep-cli/src/scala/bleep/Main.scala
- bleep.yaml
- try to fix arg0 support by copying what scala-cli does (again)
> upgrade to graalvm 22.3.0

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/commands/BuildDiff.scala
- bleep-cli/src/scala/bleep/commands/BuildDiffBloop.scala
- bleep.yaml
> add command `bleep build diff bloop <...projects>`

- bleep-core/src/scala/bleep/CoursierResolver.scala
- bleep-core/src/scala/bleep/Started.scala
- bleep-core/src/scala/bleep/UserPaths.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
- bleep-model/src/scala/bleep/FetchJvm.scala
- scripts/src/scala/bleep/scripts/GenDemoVideos.scala
- scripts/src/scala/bleep/scripts/GenNativeImage.scala
- scripts/src/scala/bleep/scripts/It.scala
> Introduce bleep-level JVM cache to avoiding coursier redownloading the index all the time

- bleep-cli/src/scala/bleep/commands/Scalafmt.scala
- bleep-tests/src/scala/bleep/ScalafmtTest.scala
fixes https://github.com/oyvindberg/bleep/issues/234
/cc @baccata
> Scalafmt: fix parsing version

- .github/workflows/build.yml
Attempts to address libc incompatibility errors experienced in CIs
> Pin gha ubuntu version to 20.04

- bleep-cli/src/scala/bleep/sbtimport/runSbt.scala
- bleep-model/src/scala/bleep/FetchSbt.scala
this way we avoid path problems
Fixes #248
> Download sbt launcher for sbt import

- bleep-core/src/scala/bleep/commands/Run.scala
> Run: use jvmOptions instead of java options

- bleep-core/src/scala/bleep/commands/SetupDevScript.scala
It doesn't need to be Bash, right?
> SetupDevScript /bin/sh

- bleep-core/src/scala/bleep/CoursierResolver.scala
This is the only build which (at least for now) will be mounted in an IDE where it's useful
> Only download sources for maven artifacts for BSP build variant.

- .github/workflows/build.yml
- README.md
- bleep.yaml
move `generate-resources` script to `sourcegen`
> Bump to 0.0.1-M25

- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
- bleep-core/src/scala/bleep/logging/jsonEvents.scala
- bleep-tests/src/scala/bleep/IntegrationTests.scala
> Integration tests should decode json events

- bleep-cli/src/scala/bleep/Main.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
Today, I realized that running `bleep --help` gives a non-zero exit code. This is a fix for that.
> Do not exit on error when no error occurred

- bleep-core/src/scala/bleep/packaging/GenLayout.scala
- bleep-tests/src/scala/bleep/packaging/PublishSnapshotTests.scala
- snapshot-tests/publish/pom.xml
> Add exclusions to GenLayout for maven

- bleep-cli/src/scala/bleep/Main.scala
> Fix help text for `--directory`

- bleep-cli/src/scala/bleep/commands/Import.scala
- bleep-cli/src/scala/bleep/sbtimport/ImportInputData.scala
- bleep-tests/src/scala/bleep/IntegrationSnapshotTests.scala
closes https://github.com/oyvindberg/bleep/issues/341
> fix: don't fail when file reading binary files during import

- bleep-cli/src/scala/bleep/commands/CoursierInstallation.scala
- bleep-cli/src/scala/bleep/commands/InstallBashTabCompletions.scala
- bleep-cli/src/scala/bleep/commands/InstallZshTabCompletions.scala
> fix: always include bleep as cmd for zsh tab completions

- bleep-cli/src/resources/META-INF/native-image/org.scala-lang/scala-lang/reflect-config.json
- bleep.yaml
This should fix #378
Tested with Neovim 0.10.0 and metals 1.3.1.
I've also tested it with VsCode and it seems to work fine there.
When running bleep compile <project> --watch I am seeing errors reported twice, but I am not sure if that is related to this in any way.
> Bleep did not work for Neovim/VsCode for me. This should fix it

- bleep-cli/src/scala/bleep/Main.scala
- bleep-core/src/scala/bleep/BleepCommandRemote.scala
- bleep-core/src/scala/bleep/bsp/BleepBspServer.scala
- bleep-core/src/scala/bleep/commands/ListTests.scala
also continue with warning if BSP wanted to test/compile a non-existing project
> add `bleep list-tests <...projects>` command

- .github/workflows/build.yml
- .gitmodules
- bleep-cli/src/scala/bleep/commands/SetupIde.scala
- bleep-core/src/scala/bleep/bsp/BleepBspServer.scala
- bleep-core/src/scala/bleep/bsp/BleepRifleLogger.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
- bleep.yaml
- scripts/src/scala/bleep/scripts/GenNativeImage.scala
Preparing to switch back to scalacenter/bloop so we can start merging in the pending PRs.
> Switched bloop back to scalacenter/bloop

- .github/workflows/build.yml
blocked on
* https://github.com/oyvindberg/bleep/pull/407#issuecomment-2275734185 /cc @KristianAN
> yaml-ls-check

- bleep-cli/src/resources/META-INF/native-image/org.scala-lang/scala-lang/reflect-config.json
- bleep-core/src/scala/bleep/commands/Test.scala
built native image locally and tested.
closes: #411
> Fix: added missing classes to reflect-config.json

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/commands/BuildMoveFilesIntoBleepLayout.scala
- bleep-cli/src/scala/bleep/commands/BuildProjectRename.scala
- bleep-cli/src/scala/bleep/commands/commit.scala
- bleep-model/src/scala/bleep/model/JsonList.scala
[Kapture 2024-11-14 at 13.32.23.webm](https://github.com/user-attachments/assets/49683a94-304f-46bf-9f57-b94b9bf9d38f)
> add `bleep build project-rename`

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/commands/BuildProjectMove.scala
[Kapture 2024-11-14 at 13.37.04.webm](https://github.com/user-attachments/assets/85c4fbb0-bb63-4258-87f1-e4bbbf6e50a8)
> add `bleep build projects-move <new-parent-dir>` <projects>

- README.md
- bleep-core/src/scala/bleep/commands/SetupDevScript.scala
- bleep.yaml
- add windows batch script for dev
- bump coursier since it was causing weird `null` folder to be created.. (fixed in newer versions)
> Implement generating dev script on Windows
