oyvindberg/bleep

- bleep-core/src/main/scala/bleep/model.scala
JSON does not support to comment out lines. Filter out lines to make it a bit easier to work with the build configuration.
> feat: option to comment out lines in the bleep.json file

- bleep-core/src/main/scala/bleep/CoursierResolver.scala
- bleep-core/src/main/scala/bleep/bootstrap.scala
- bleep/src/test/scala/bleep/OutputSnapshotTest.scala
Expects a format on the lines of:
```
{
"<url>": {
"user": "user", //optional
"password": "password", //optional
"realm": "Realm of maven central, nexus", //optional
"optional": false //optional,
"headers": {"Authentation": "foobar"}, //optional
"httpsOnly": true, // optional
"passOnRedirect": true //optional
}
}
```
Failing to parse will log a messsage to the console.
We will also output an info message if we dont find this file.
The file is expected to be in a directory according to the [XDG](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) spec, or
whatver is native to the current platform.
> Add coursier resolver authentication

- bleep-core/src/main/scala/bleep/model.scala
We now support a potential richer model for when we need to include classifiers, exclusions or optionallity
```json
"dependencies":  [
"org.http4s::http4s-client:0.23.1",
{ 
"module": "org.http4s::http4s-ember-client:0.23.1",
"excludes": ["org.http4s::http4s"],
"optional": false,
"classifier": "sources"
}
]
```
> Support a richer model for dependencies

- bleep-core/src/main/scala/bleep/Paths.scala
Fix of https://github.com/oyvindberg/bleep/pull/44/files#diff-a281fe835a2138723ccf0f9b5a508632df22792d9060cd60ff9006fa481139d3R14
The arguments to `ProjectDirectories.from` are different from `AppDirs#getUserCacheDir`
```
public static ProjectDirectories from​(java.lang.String qualifier, java.lang.String organization, java.lang.String application)
```
https://javadoc.io/doc/dev.dirs/directories/latest/dev/dirs/ProjectDirectories.html
```
abstract String getUserCacheDir(String appName, String appVersion, String appAuthor)
```
https://javadoc.io/doc/net.harawata/appdirs/latest/net/harawata/appdirs/AppDirs.html
> Repair ProjectDirectories.from arguments

- bleep-core/src/main/scala/bleep/Options.scala
- snapshot-tests/converter/bleep.yaml
- snapshot-tests/create-new-build/bleep.yaml
- snapshot-tests/doobie/bleep.yaml
- snapshot-tests/http4s/bleep.yaml
- snapshot-tests/tapir/bleep.yaml
list of strings looks horrible when ~all values starts with a dash
> render options as string in yaml instead. 

- .github/workflows/build.yml
the `ENV: CI` was lost at some point, and with it the sneaky coursier cache where the snapshot tests place resolving cache within the coursier folder. 
there is still more to be done here
> Speedup CI build somewhat

- .gitmodules
- bleep-cli-test/src/scala/bleep/TemplateTest.scala
- bleep-cli/src/scala/bleep/Main.scala
- bleep-core/src/scala/bleep/LogPatterns.scala
- bleep-core/src/scala/bleep/bootstrap.scala
- bleep-core/src/scala/bleep/bsp/BleepRifleLogger.scala
- bleep-core/src/scala/bleep/cli.scala
- bleep-core/src/scala/bleep/commands/Run.scala
- bleep-core/src/scala/bleep/constants.scala
- bleep-core/src/scala/bleep/internal/BspClientDisplayProgress.scala
- bleep-core/src/scala/bleep/logging/Formatter.scala
- bleep-core/src/scala/bleep/logging/LogLevel.scala
- bleep-core/src/scala/bleep/logging/LoggerFn.scala
- bleep-core/src/scala/bleep/logging/Pattern.scala
- bleep-core/src/scala/bleep/logging/TypedLogger.scala
- bleep-core/src/scala/bleep/logging/jsonEvents.scala
- bleep-core/src/scala/bleep/logging/package.scala
Add `path` as a structured thing to replace string concatenation which was used before
This way output looks decent, filtering works and so on.
before:
after:
> logging: transfer log events from child processes as json. 

- bleep-cli/src/scala/bleep/Main.scala
> launcher: Can only use `Execve` if we're in a native-image

- .github/workflows/build.yml
- bleep.yaml
build native-image for ubuntu on older version. Fixes (#235)
Followup to #236
- I suppose it'll be forward compatible
- note: there is a migration step here. The cs launch things are to launch bleep on the JVM in order to produce a release with lower version of glibc
> Build native image for ubuntu on older version

- schema.json
This change allows using `./` as a relative path.
In a project I tried to convert, `bleep import` created a file with `templates.template-common.folder: ./`, which is correct, but was refused by the schema.
> Schema: Allow RelPath to point to current directory

- coursier-channel.json
Closes https://github.com/oyvindberg/bleep/issues/267
* Coursier is set to standardise on `aarch64` (see https://github.com/coursier/coursier/pull/2651/files) 
* I'm using an M1 and `sys.props("os.arch")` gives me `aarch64`, so I assume it's gonna be the same for all macs with an arm64 architecture, even in the current state without that coursier PR merged 
The fix was tried locally via the following command : 
``` 
cs install --channel file:///fully/qualified/path/to/coursier-channel.json bleep
```
which happens to work
> Amend coursier channel so that cs finds aarch64-apple-darwin

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/bsp/BspImpl.scala
- bleep-cli/src/scala/bleep/commands/SetupIde.scala
- bleep-core/src/scala/bleep/ExitCode.scala
- bleep-core/src/scala/bleep/bootstrap.scala
- bleep-core/src/scala/bleep/commands/Run.scala
- bleep-core/src/scala/bleep/internal/bleepLoggers.scala
- bleep-core/src/scala/bleep/internal/fatal.scala
- bleep-core/src/scala/bleep/internal/jvmRunCommand.scala
- bleep-core/src/scala/bleep/logging/Loggers.scala
- bleep-core/src/scala/bleep/logging/TypedLogger.scala
- bleep-core/src/scala/bleep/logging/TypedLoggerResource.scala
- bleep-core/src/scala/bleep/logging/jsonEvents.scala
- bleep-core/src/scala/bleep/logging/package.scala
- bleep-tests/src/scala/bleep/IntegrationTests.scala
- bleep-tests/src/scala/bleep/testing/SnapshotTest.scala
- scripts/src/scala/bleep/scripts/GenDemoVideos.scala
- recover lost log messages, fallout from 35278814
- there were still some holes left when json log messages got through. hopefully the problem is gone now
- by using `TypeLoggerResource` to close loggers we can now get away without flushing to disk while running, but do so on process exit. this has the potential to speed things up
- introduced an `ExitCode` structure to separate final logging after program completion and exiting process. this is to make sure we have time to flush first. This means that `fatal` does not call `System.exit` anymore
- add support for `bleep setup-ide` through JVM, towards #260. There is also a `--force-jvm` flag
- collected all loggers in `bleepLoggers`
> Revamp logging, `Main`, process exit a bit more, allow `bleep-setup-ide` to boot JVM

- README.md
Hi, thanks for this project. It's early days but I'm super excited by the potential and it's working great for us so far.
When attempting to contribute, I checkout the source but I could not run `bleep compile`, there were some errors regarding undefined types, like `bleep-model@jvm213 not found: type BleepVersion`
I looked at the CI and saw that you run `bleep generate-resources` before compiling, so I tried that.
I'm assuming this won't be required in the future, when things like https://github.com/oyvindberg/bleep/issues/19 are resolved.
> Improve contributor experience

- bleep-model/src/scala/bleep/FetchJvm.scala
- bleep-model/src/scala/bleep/model/Jvm.scala
As seen in #278, caching the system's JVM can be tricky because updating JAVA_HOME will have no effect as the cache entry remains and the new JAVA_HOME is unused.
Closes https://github.com/oyvindberg/bleep/issues/278
Created as a draft because I'm not sure if you'd like test for this and I still need to manually test this here.
> Do not cache the system's jvm

- bleep-cli/src/scala/com/monovore/decline/Completer.scala
There is a case `Opt.OptionalOptArg` which is unimplemented, because it didn't exist when I wrote the support originally.
I don't have the time to fix it properly now, but this will at least unbreak all the other completion
> Fix autocompletion

- bleep-cli/src/scala/bleep/commands/CompileServerStopAll.scala
- bleep-core/src/scala/bleep/UserPaths.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
There is apparently a 100 char limit in place, this makes it a bit more probable that the generated names are short enough.
Fixes #281
This is an example socket name on my machine: `/Users/oyvind/Library/Caches/build.bleep/socket/graalvm-java17_22.3.0`, which is 70 chars. This leaves room for a username of ~36 chars
The configuration file now lives here `/Users/oyvind/Library/Application Support/build.bleep/config.yaml`
> Shorten path to cache/config directories and socket names

- .github/workflows/build.yml
- bleep-cli/src/scala/bleep/bsp/BspImpl.scala
- bleep-core/src/scala/bleep/BleepCommandRemote.scala
- bleep-core/src/scala/bleep/BleepExecutable.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
Followup to b1122ee8: allow M24 to build newest code without supplying bleep literal to script
> `BleepExecutable` followup

- bleep-core/src/scala/bleep/bootstrap.scala
This is just a small PR to tweak the error message that shows up when running a script that fails. Feel free to close it if you prefer the original, I just felt like `failed :(` was unhelpful
> Tweak error message for when script run fails

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/bsp/BspImpl.scala
- bleep-core/src/scala/bleep/BleepCacheLogger.scala
- bleep-core/src/scala/bleep/bsp/BleepBspServer.scala
- bleep-core/src/scala/bleep/bsp/BuildChangeTracker.scala
- bleep-core/src/scala/bleep/bsp/ExceptionHandler.scala
- bleep-core/src/scala/bleep/internal/bleepLoggers.scala
- bleep-core/src/scala/bleep/internal/fatal.scala
One part of the changeset is rather experimental: I'm experimenting with differentiating between intellij and metals since they behave differently.
For metals we always close the BSP connection on any failure, while for intellij it seems to work better to show and error and let it try again.
Hery likely some followup for this
> Improve BSP error handling

- bleep-cli/src/scala/bleep/bsp/BspImpl.scala
- bleep-core/src/scala/bleep/Prebootstrapped.scala
- bleep-core/src/scala/bleep/bsp/BleepBspServer.scala
- bleep-core/src/scala/bleep/bsp/BuildChangeTracker.scala
- bleep-core/src/scala/bleep/internal/Throwables.scala
- The current bsp4j design is unsustainably bad, but fixing it takes a lot of work, so we're patching it.
- exceptions trigger another way of failing, so I worked around with a few well places `Try`s
- Fixed a bug which held onto old state in the presence of a broken build (causing watch mode to flip the old state back in)
- send warnings to IDE through BSP to complain about broken build
- reinstate running sourcegen for compile task (should probably be for other BSP methods as well, but let's see how far `compile` takes us).
- Fixes a bug where a build which is broken on BSP boot will both fail and hang. Now it won't hang anymore, but it's all brittle.
> Towards stabilizing BSP

- bleep-cli/src/scala/bleep/sbtimport/buildFromBloopFiles.scala
- bleep-core/src/scala/bleep/GenBloopFiles.scala
- bleep.yaml
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/myapp@js213.json
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/myapp@jvm213.json
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/tests@js213.json
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/tests@jvm213.json
Enabling `strict` in build didn't bring in the good new stuff for scala 3.3.0
> integrate newer sbt-tpolecat

- bleep-cli/src/scala/bleep/Main.scala
- bleep-tests/src/scala/bleep/CliInvocationTest.scala
I've never seen a CLI tool outputting help messages on stderr until now. Looks wrong to me.
Also improved the failure message with some more end-user actionable suggestion. Users couldn't see the code comment… :smile:
> Move help output form stderr to stdout

- bleep-cli/src/scala/bleep/Main.scala
- bleep-core/src/scala/bleep/commands/PublishLocal.scala
- bleep-core/src/scala/bleep/packaging/GenLayout.scala
- bleep-core/src/scala/bleep/packaging/packageLibraries.scala
- scripts/src/scala/bleep/scripts/PublishLocal.scala
Hey @oyvindberg , hope you're good.
I've opened this PR, you can close if you're not interested as I did not discuss that with you prior to opening that. But I figured that the changes were small enough to avoid the overhead of an issue prior to a PR, when the code could speak for itself instead.
Basically, we want to use the manifest creator to add some information the jars we publish. We've had two issues:
1. publish local options don't allow to customize the manifest creator: https://github.com/oyvindberg/bleep/commit/3873f6d99352abe8b2ad358f9e3c540d4d483783
2. the manifest creator receives an optional project name but it's always none: https://github.com/oyvindberg/bleep/commit/e07c2c0adc51bc3e8b8c55e8234bb859ccf38bd0
Happy to make any changes you'd like to see if you think this make …
> Publishing issues

- .github/workflows/build.yml
- bleep-cli/src/resources/META-INF/native-image/org.scala-lang/scala-lang/proxy-config.json
- bleep-cli/src/resources/META-INF/native-image/org.scala-lang/scala-lang/reflect-config.json
- bleep-cli/src/scala/bleep/bsp/BspImpl.scala
- bleep-cli/src/scala/bleep/commands/CompileServerStopAll.scala
- bleep-cli/src/scala/bleep/commands/SetupIde.scala
- bleep-core/src/scala/bleep/BleepCommandRemote.scala
- bleep-core/src/scala/bleep/bsp/BleepBspServer.scala
- bleep-core/src/scala/bleep/bsp/BleepRifleLogger.scala
- bleep-core/src/scala/bleep/bsp/BspThreads.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
- bleep-core/src/scala/bleep/commands/Compile.scala
- bleep-core/src/scala/bleep/commands/Dist.scala
- bleep-core/src/scala/bleep/commands/PublishLocal.scala
- bleep-core/src/scala/bleep/commands/Run.scala
- bleep-core/src/scala/bleep/commands/Script.scala
- bleep-core/src/scala/bleep/commands/SourceGen.scala
- bleep-core/src/scala/bleep/commands/Test.scala
- bleep-core/src/scala/bleep/discoverMain.scala
- bleep-core/src/scala/bleep/internal/BspClientDisplayProgress.scala
- bleep-core/src/scala/bleep/internal/DoSourceGen.scala
- bleep.yaml
Upstream moved, and some follow-up changes need
to be included as well.
Graal Native Image also needed some adjustments.
**Important:**
This PR depends on https://github.com/scala-cli/bloop-core/pull/153.
I'm not entirely sure about the build changes. But there seem to be some dependencies missing for 2.12. Should support for Scala 2.12 be dropped maybe altogether?
> Bloop-rifle update

- .github/workflows/build.yml
- bleep-tests/src/scala/bleep/CliInvocationTest.scala
- bleep.yaml
some more fallout from the bloop upgrade it seems. one detail which was wrong on my part, and now the native-image binary seems unable to run tests. and CI considers those tests green! pff
> Fix build for releases

- .github/prepare-release.sh
- .github/workflows/build.yml
- .gitmodules
- bleep-cli/src/scala/bleep/commands/BuildDiff.scala
- bleep-cli/src/scala/bleep/commands/BuildDiffBloop.scala
- bleep-cli/src/scala/bleep/commands/BuildMoveFilesIntoBleepLayout.scala
- bleep-cli/src/scala/bleep/commands/BuildShow.scala
- bleep-cli/src/scala/bleep/commands/CompileServerSetMode.scala
- bleep-cli/src/scala/bleep/commands/CompileServerStopAll.scala
- bleep-cli/src/scala/bleep/sbtimport/buildFromBloopFiles.scala
- bleep-core/src/scala/bleep/GenBloopFiles.scala
- bleep-core/src/scala/bleep/bsp/BleepRifleLogger.scala
- bleep-core/src/scala/bleep/bsp/SetupBloopRifle.scala
- bleep-core/src/scala/bleep/commands/Clean.scala
- bleep-core/src/scala/bleep/commands/Evicted.scala
- bleep-site-in/installing.mdx
- bleep.yaml
- scripts/src/scala/bleep/scripts/GenNativeImage.scala
- snapshot-tests-rewrites/drop-feature-flag/doobie/bleep.yaml
- snapshot-tests-rewrites/drop-feature-flag/tapir/bleep.yaml
- snapshot-tests-rewrites/keep-selected-projects/doobie/bleep.yaml
- snapshot-tests-rewrites/keep-selected-projects/tapir/bleep.yaml
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/myapp@js3.json
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/myapp@jvm3.json
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/tests@js3.json
- snapshot-tests/create-new-build/bootstrapped/.bleep/builds/normal/.bloop/tests@jvm3.json
- snapshot-tests/create-new-build/build/bleep.yaml
- snapshot-tests/doobie/imported/bleep.yaml
- snapshot-tests/tapir/imported/bleep.yaml
- built with newest graalvm native-image
- newest bloop-rifle
- bump most deps
- new sbt-tpolecat (so that `strict` works better with newer scala versions)
- add macos m1 github runner, so we automatically get releases on that platform as well without manual steps
Windows support was especially problematic this time around. I'm not sure if it actually works right now. 
What I see when running CI is that the new binary does compile things ok, but then receives an `Error:  bloop: Caught java.lang.InterruptedException` after the compile is done. 
I'm going to leave it at that, until a windows enthusiast comes along and fixes it.
> Tech refresh

- bleep-cli/src/scala/bleep/Main.scala
- bleep-cli/src/scala/bleep/commands/InstallBashTabCompletions.scala
- bleep-cli/src/scala/bleep/commands/InstallZshTabCompletions.scala
This will allow users that have bespoke systems to pipe and modify the completions as they see fit, increasing the number of systems shell completions can be installed too.
> Added flag to send shell completions to stdout.

- schema.json
Last commit introduced a slight bug where it would complain about missing jsSplitStyle even when it should not be set. e.g it would complain for
platform:
name: jvm
> HOTFIX - Fix to logic in schema valiation

- bleep-cli/src/scala/bleep/Main.scala
- bleep-core/src/scala/bleep/Commands.scala
- bleep-core/src/scala/bleep/commands/ListTests.scala
- bleep-core/src/scala/bleep/commands/Test.scala
- bleep-model/src/scala/bleep/BleepException.scala
So this is a very crude implementation that should work once https://github.com/scalacenter/bloop/pull/2360 is merged and bleep uses mainline bloop. 
However the cli interface is not great as it will look like bleep test project -o TestSuiteOne -o TestSuiteTwo ... and so on. I don't think it's possible to combine Option and arguments in decline? So I'm guessing here we have to use arguments and just do some parsing to make it look nice?
Update:
It is now possible to specify which test suites to run using the -o or
--only syntax.
The tests can be specified using the class name of the test suite or by
using the fully qualified name.
Example:
bleep test app-tests -o TestSuiteOne --only TestSuiteTwo
fully qualified:
bleep test app-tests -o com.foo.TestSuiteThree
> --test-only

- bleep-core/src/scala/bleep/GenBloopFiles.scala
Tested on a JS project, setting the different split styles now works.
> bugfix: fix missing generation of bloop config modulesplitstyle

- bleep-cli/src/scala/bleep/Main.scala
Currently it requires you to write `----main-class`.
> Remove extra dashes for setup-dev-script option

- README.md
Fixes #437 
The badge itself links to the invite link for the Scala Discord as a whole, the "#tooling channel" text links to the specific channel
> Update README to link to Discord

- bleep-core/src/scala/bleep/packaging/CoordinatesFor.scala
- bleep-model/src/scala/bleep/BuildPaths.scala
- when publishing, move leading prefixes to `groupId` by default
> allow prefixes separated by `/` in `model.ProjectName`.

- bleep-core/src/scala/bleep/Prebootstrapped.scala
- bleep-site-in/usage/stable-builds.mdx
This does not interfere with the build model, yet provides a simple way of disabling the warning when the JVM version is managed outside of bleep.
Especially useful for Nix users and the likes, where dynamically linked software can not be run without extra effort.
> Add way to disable warning when using external JVM.

- bleep-core/src/scala/bleep/BleepCommandRemote.scala
- bleep-core/src/scala/bleep/GenBloopFiles.scala
- bleep-core/src/scala/bleep/internal/conversions.scala
- bleep-model/src/scala/bleep/model/NativeBuildTarget.scala
- bleep-model/src/scala/bleep/model/Platform.scala
- bleep-model/src/scala/bleep/rewrites/Defaults.scala
- bleep.yaml
- schema.json
When linking SN projects the user can specify to link as an application ,the most common and the default, or the user can specify a dynamic or static library.
This is a new configuration option that has been added to bloop-config for better support for linking without a main class when building SN libraries
> Support for defining NativeBuildTarget

- bleep.yaml
- scripts/src/scala/bleep/scripts/GenNativeImage.scala
Bloop version with support for linking through bsp
> deps: bloop-config 2.3.0->2.3.1, bloop-rifle 2.0.5->2.0.7

- .github/workflows/build.yml
Ubuntu 20.04 is now officially deprecated in github actions
> ci: Upgrade ubuntu runner to ubuntu 22.04
